config/routes.rb
Rails.application.routes.draw do
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/404', to: 'errors#not_found', via: :all
  get '/legal', to: 'pages#legal', as: 'legal'
  get '/team', to: 'pages#team', as: 'team'  
  root to: 'pages#home'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/data_base.rb
class DataBase < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def description
    "Je suis #{job.downcase} chez Havior Company depuis #{years} ans
    et j'aime accompagner les entreprises pour que leur image les aide
    dans leurs projets. Et sinon je suis passionné de #{hobby}."
  end

  def name
    "#{first_name&.capitalize} #{last_name&.capitalize}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  # uncomment to raise error if authorize is not call in controller
  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def configure_permitted_parameters
    user_data = [
      :nick_name,
      :admin,
      :senior,
      :first_name,
      :last_name
    ]
    # raise
    devise_parameter_sanitizer.permit(:sign_up, keys: user_data)
    devise_parameter_sanitizer.permit(:account_update, keys: user_data)
  end


  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def user_not_authorized
    flash[:alert] = "Vous n'êtes pas autorisés à réaliser cette action."
    redirect_to(root_path)
  end

end

app/controllers/errors_controller.rb
   class ErrorsController < ApplicationController
      skip_before_action :authenticate_user!
      def not_found
        render status: 404
      end

      def internal_server_error
        render status: 500
      end
    end

app/controllers/pages_controller.rb
    class PagesController < ApplicationController
      skip_before_action :authenticate_user!, only: [:home, :legal, :team]

      def home
      end

      def team
      end

      def legal
      end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end

  # def meta_keywords
  #   content_for?(:meta_keywords) ? content_for(:meta_keywords) : DEFAULT_META["meta_keywords"]
  # end
end

app/views/layouts/_cookies_banner.html.erb
<div id="cookiesBanner" class="cookies-banner py-3  d-none position-fixed w-100">
  <div class="d-md-flex container align-items-center">
    <p class="mb-md-0 flex-grow-1 text-white mr-md-3">
      Nous utilisons des cookies, dont des cookies tiers (Google) pour vous offrir une expérience utilisateur de qualité ainsi que pour suivre et analyser le trafic sur le site. En cliquant sur « Accepter », vous acceptez que nous utilisions ces cookies. Vous pouvez à tout moment modifier vos paramètres de cookies. Pour cela, nous vous invitons à consulter notre Politique de confidentialité en cliquant sur « Personnaliser »
      <br><%= link_to "En savoir plus", legal_path, target: "_blank", class: "link-no-decoration text-cookie" %>
    </p>
    <div class="d-flex">
      <div id="cookiesGlobalConsent" class="btn btn-cookie font-size-12px me-3">Accepter</div>
      <div class="btn btn-cookie font-size-12px" data-bs-toggle="modal" data-bs-target="#cookiesModal">Personnaliser</div>
    </div>
  </div>
</div>
<div class="modal fade font-size-14px font-montserrat" id="cookiesModal" tabindex="-1" role="dialog" aria-labelledby="cookiesModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered max-width-650px" role="document">
    <div class="modal-content p-3 ">
      <div class="modal-header border-0 p-0">
        <%= image_tag "logo.png", width: 60 %>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body px-md-6">
        <p class="font-weight-bold title-small">Votre Accord sur l'utilisation des cookies</p>
        <p>Vous êtes libre d'activer et de désactiver à tout moment les familles de cookies suivantes :</p>
        <p class="font-weight-bold">Cookies strictement nécessaires</p>
        <div class="d-flex align-items-center justify-content-between mb-3">
          <p class="flex-grow-1 mb-0">Ils sont indispensables au bon fonctionnement du site.</p>
          <%= image_tag "check.svg", width: 25 %>
        </div>
        <p class="font-weight-bold">Cookies Statistiques</p>
        <div class="d-flex align-items-center mb-2">
          <p class="flex-grow-1 mb-0">Ils nous permettent d'établir des statistiques anonymes via Google Analytics</p>
          <div class="min-width-60px">
            <div class="toggle-slide-input">
              <input type="checkbox" name="google_analytics_consent" id="google_analytics_consent" data-analytics="<%= ENV['GOOGLE_ANALYTICS_KEY'] %>">
              <label for="google_analytics_consent"></label>
            </div>
          </div>
        </div>
      </div>
      <div class="text-center">
        <div type="button" id="cookiesConfigBtn" class="btn btn-cookie" data-bs-dismiss="modal">Je valide</div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_google_analytics.html.erb
<% if Rails.env == "production"  %>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=<%= ENV['GOOGLE_ANALYTICS_KEY'] %>"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', "<%= ENV['GOOGLE_ANALYTICS_KEY'] %>");
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "layouts/google_analytics" %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <%= yield(:robots) %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <!-- 	prevent Chrome animation on loading -->
    <script type="text/javascript"> </script>
  </head>
  <body>
    <%= render "layouts/cookies_banner" %>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="wrapper">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>

    <script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "Organization",
        "name": "yourdomain",
        "url": "https://www.yourdomain.com/",
        "logo": "",
        "contactPoint": [{
          "@type": "ContactPoint",
          "url": "https://www.yourdomain.com",
          "email": "contact@yourdomain.com",
          "telephone": "+33-30000000",
          "contactType": "customer service"
        }],
        "image": "",
        "description": ""
      }
    </script>
  </body>
</html>

app/views/pages/home.html.erb
<%= content_for :meta_title, "Yourdomain - Your Meta" %>

<div class="container page-min-height py-5">
  <div class="banner">
    <%= image_tag "havior-banner.jpg" %>
    <div class="banner-infos text-center w-100">
      <h1>Havior Company</h1>
      <p>Votre image et notre priorité</p>
    </div>
  </div>
</div>

app/views/pages/legal.html.erb
<% content_for(:robots) do %>
  <meta name="robots" content='noindex, nofollow'>
<% end %>

<div class="container page-min-height">
  <h1>Pages#Legal</h1>
  <p>Find me in app/views/pages/legal.html.erb</p>
  <div>
    À tout moment, l’Utilisateur peut faire le choix d’exprimer et de modifier ses souhaits en matière de Cookies. <a href=<%=ENV["DOMAIN_PROD"]%>><%=ENV["DOMAIN_PROD"]%>/</a> pourra en outre faire appel aux services de prestataires externes pour l’aider à recueillir et traiter les informations décrites dans cette section.</p>
    	      À tout moment, l’Utilisateur peut faire le choix d’exprimer et de modifier ses souhaits en matière de Cookies en cliquant sur le lien ci-dessous. <a href=<%=ENV["DOMAIN_PROD"]%>><%=ENV["DOMAIN_PROD"]%></a> pourra en outre faire appel aux services de prestataires externes pour l’aider à recueillir et traiter les informations décrites dans cette section.</p>
    <div class="d-flex justify-content-center mb-4">
      <div class="btn btn-cookie font-size-16px py-2" data-toggle="modal" data-target="#cookiesModal">PERSONNALISER LES COOKIES</div>
    </div>
  </div>
</div>

app/views/pages/team.html.erb
<% content_for(:robots) do %>
  <meta name="robots" content='noindex, nofollow'>
<% end %>


<div class="container">
    <h1 class="text-center p-5">Notre équipe</h1>
    <div class="d-flex justify-content-center p-3">
        <div>
            <%= render User.where(employee: true).shuffle %>
        </div>
    </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer d-flex justify-content-between align-items-center">
  <div class="footer-links">
  </div>
  <div class="footer-copyright d-flex flex-column">
    © 2018 <%=ENV["DOMAIN"] || "localhost:3000"%>
    <%= link_to legal_path do %>
      Mentions légales
    <% end %>
    <%= link_to "https://www.mihivai.com/", target: "_blank" do %>
      Site réalisé par Mihivai
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-mihivai">
  <!-- Logo -->
  <a href="/" class="navbar-mihivai-brand">
    <%= image_tag "logo.png" %>
  </a>

  <div class="d-none d-md-block">
    <div class="d-flex align-items-center justify-content-between">
      <%= link_to "Nos Services", "/", class: "navbar-mihivai-item navbar-mihivai-link" %>
      <%= link_to "Notre équipe", team_path, class: "navbar-mihivai-item navbar-mihivai-link" %>      
      <%= link_to "Mon compte", edit_user_registration_path, class: "navbar-mihivai-item navbar-mihivai-link" %>
      <% if user_signed_in? %>
        <% if current_user.admin %>
          <%= link_to "Back Office", "/admin", class: "navbar-mihivai-item btn btn-warning" %>
        <% end %>
        <%= link_to t(".sign_out", default: "Se déconnecter"), destroy_user_session_path, method: :delete , class: "navbar-mihivai-item navbar-mihivai-link"%>
      <% else %>
        <%= link_to t(".sign_in", default: "Se connecter"), new_user_session_path , class: "navbar-mihivai-item navbar-mihivai-link"%>
      <% end %>
    </div>
  </div>

  <div class="d-block d-md-none">
    <div class="navbar-dropdown">
      <input id="toggle" type="checkbox"/>
      <label class="hamburger" for="toggle">
        <div class="top"></div>
        <div class="meat"></div>
        <div class="bottom"></div>
      </label>

      <div class="nav">
        <div class="nav-wrapper">
          <nav class= "d-flex flex-column">
            <%= link_to "Accueil", root_path, class: "navbar-link" %>
            <% if user_signed_in? %>
              <%= link_to "Se Déconnecter", destroy_user_session_path, class: "navbar-link", method: :delete %>
            <% else %>
              <%= link_to "Créer un Compte", new_user_registration_path, class: "navbar-link" %>
              <%= link_to "Se Connecter", new_user_session_path,  class: "navbar-link" %>
            <% end %>
          </nav>
        </div>
      </div>
    </div>

  </div>
</div>

<div style="height: 70px;"></div>

app/views/users/_user.html.erb
<div class="card mb-3" style="max-width: 540px;">
    <div class="row g-0">
        <div class="col-md-4">
            <div class="d-flex align-items-center w-100 h-100">
                <%= image_tag "avatar#{user.position}.png", class: "w-100" %>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title"><%= user.name %></h5>
                <h6><i><%= user.job %></i></h6>
                <p class="card-text"><%= user.description %></p>
                <p class="card-text"><small class="text-muted"><%= user.email %></small></p>
            </div>
        </div>
    </div>
</div>